### ISSUE TITLE
Audit Circle Meeting 4 - 28th April 2022 - Agenda & Notes 

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Auditing/Audit-Hub-Coordination#22]
## Audit Circle Meeting 4 - 28th April 2022 - Agenda & Notes 

https://quality-assurance-dao.gitbook.io/audit-circle/project-management/meetings/

**Comment by Andre-Diamond** [comment]
Paid Megan $100 for Meeting minutes

**Comment by PolymathGirl** [comment]
[Here is the Google Doc link that I drafted it up from/on](https://docs.google.com/document/d/1ESAsGC6BQVEDOrxj_1J3O7axI-lbM0BuMe7-JgMri6g/edit) 

And attached should hopefully also be the edited, corrected Transcript, from what otter.ai had generated. 

[Audit Circle Meeting 4 - Megan's edits.docx](https://github.com/Catalyst-Auditing/Audit-Circle-Coordination/files/8607860/Audit.Circle.Meeting.4.-.Megan.s.edits.docx)

As I mentioned in the [Discord](https://discord.com/channels/942395447685828678/969194888740614154), I highlighted what seemed like important points, embedded a bunch of hyperlinks to what seemed important, corrected a boatload of AI transcription errors, etc., so don't ignore or overlook the transcript, since it should have a lot of great information embedded as well, not just 100% in my Google Doc typed up notes. 

Also, if there's a certain angle that I'm doing these "wrong" or types of things you'd rather me have focused more on, please let me know, since I'm still kind of "finding my feet" and making it up as I go, figuring it out along the way, between my personal notetaking style and what other folks probably might want.
